name: Laravel CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kodenya
    - uses: actions/checkout@v3

    # 2. Setup PHP (Kita pakai PHP 8.1 atau 8.2 yang umum untuk Laravel modern)
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.19' # Sesuaikan jika error, coba ganti ke 8.0 atau 8.2
        extensions: mbstring, dom, fileinfo, sqlite3
        coverage: xdebug

    # 3. Copy file .env
    # Di server CI, file .env asli tidak ada (karena di-ignore git), jadi kita copy dari example
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # 4. Install Dependency (Composer)
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # 5. Generate Application Key
    # Laravel butuh key enkripsi agar bisa jalan
    - name: Generate key
      run: php artisan key:generate

    # 6. Set Directory Permissions (Opsional tapi seringkali mencegah error)
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # 7. Create Database (SQLite)
    # Kita buat file kosong untuk database SQLite
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    # 8. Execute tests (Unit Tests)
    # Kita paksa pakai SQLite via environment variables agar tidak perlu MySQL
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit